# Welcome to Chinaxiang' personal page!
lang: zh_CN
title: 欢迎来到
author: Litter
email: forkmail@qq.com
description: > 
  习惯了安逸，经不住生活。
baseurl: ""
url: "https://Jlitter.github.io"
github_username:  Jlitter
twitter_username: ""

minima:
  date_format: "%b %-d, %Y"

timezone: Asia/Shanghai

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-paginate
  - jekyll-sitemap

paginate: 15
paginate_path: "/blog/p:num"
